name: Miles Docker Push CI/CD

on:
  push:
    tags:
      - docker/*

jobs:
  Project-CICD:
    runs-on: ubuntu-latest
    steps:
      - name: ë¸Œëœì¹˜ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v4

      - name: Node í™˜ê²½ ì„¤ì¹˜
        uses: actions/setup-node@v4

      - name: í”„ë¡œì íŠ¸ ì˜ì¡´ì„± ì„¤ì¹˜
        run: |-
          yarn install
          echo "ğŸ› ï¸ ì„¤ì¹˜ ì™„ë£Œ"

      - name: ìœ ë‹› í…ŒìŠ¤íŠ¸
        run: |-
          yarn test --coverage
          echo "ğŸ§ª ìœ ë‹› í…ŒìŠ¤íŠ¸ í†µê³¼"

      - name: í”„ë¡œì íŠ¸ ë¹Œë“œ
        run: |-
          yarn build

  Docker-Build:
    needs: Project-CICD
    runs-on: ubuntu-latest
    steps:
      - name: ë¸Œëœì¹˜ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: kyw05171@gmail.com
          password: goeotod1!@12

      - name: Docker í™˜ê²½ ì„¤ì¹˜
        uses: docker/setup-buildx-action@v3

      - name: Image build ë° push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile.dev
          tags: chocobe/github-actions:v5
          context: .
          push: true
